################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

# Default values for ric-robot .
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nexus3.o-ran-sc.org:10004
  repositoryCred: docker-reg-cred
  # for local testing
  #repository: ric/testsuite
  name: o-ran-sc/it-test-ric-robot
  tag: 0.3.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
robotImplementation: "ric-robot"

config:
  #dashboardExternalIp:  REPLACE_WITH_EXTERNAL_K8_IP_OF_DASHBOARD
  #dashboardExternalPort:  REPLACE_WITH_NODEPORT_OF_KONG_PROXY_31080
  dashboardExternalIp:  192.168.130.122
  dashboardExternalPort:  32080
service:
  port: 88
  type: NodePort
  nodePort: 30209

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

### ricdeployment.robot environment variable
ric:
 platform:
  # RIC installation details.  The values
  # for these can typically be found in
  # the ricplt/ric_env.sh file from the ric
  # platform source tree
  components:
   appmgr:
   rtmgr:
   dbaas:
   e2mgr:
   e2term:

