#!/bin/bash 


#curl -X POST http://10.2.0.28:30004/v1/nodeb/endc-setup -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"ranIp": "10.2.0.28","ranPort": 36422,   "ranName":"AAAA123457"}'

#curl -X POST http://ricplt-entry:30080/e2mgr/v1/nodeb/endc-setup -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"ranIp": "10.2.0.28","ranPort": 36422,   "ranName":"AAAA123457"}'

#curl -X GET http://ricplt-entry:30080/e2mgr/v1/nodeb/AAAA000003

curl -X GET http://ricplt-entry:30080/e2mgr/v1/nodeb/$1

