#!/bin/bash

#kubectl -n ricplt logs r0-e2mgr-766fc459cb-c5m8n | grep -E --color 'gnb|10.2.0.22|successfulOutcome|initiatingMessage|e2agent|'

#kubectl -n ricplt logs r0-e2mgr-59f98778b7-8vbv2

kubectl -n ricplt logs $(kubectl -n ricplt get pods | grep -o 'deployment-r0-e2mgr[^ ]*') $1 | grep -E --color '|successfulOutcome_t|initiatingMessage_t|saved to rNib|'
